# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiblog', '0006_auto_20160716_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='count_of_users',
            field=models.IntegerField(default=0, verbose_name='Количество оценивших пользователей'),
        ),
        migrations.AddField(
            model_name='publication',
            name='full_rating',
            field=models.IntegerField(default=0, verbose_name='Общая оценка'),
        ),
    ]
