# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiblog', '0013_auto_20160720_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='is_canceled',
        ),
        migrations.AlterField(
            model_name='publication',
            name='why_not',
            field=models.TextField(blank=True, default='', max_length=600, verbose_name='Причина отказа'),
        ),
    ]
