# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiblog', '0014_auto_20160720_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='is_new',
        ),
    ]
